---
- hosts: all

  tasks:
  - name: Install htop
    apt:
      name: htop
      state: present
  - name: Install ncdu
    apt:
      name: ncdu
      state: present
  - name: Create azureuser user
    user:
      name: azureuser
      shell: /bin/bash
      state: present