---
- hosts: all

  tasks:
  - name: install example application
    copy:
      src: ansible_test_app
      dest: /tmp/
      owner: root
      group: root

  - name: Install htop
    apt:
      name: htop
      state: present
  - name: Install ncdu
    apt:
      name: ncdu
      state: present